#!/bin/bash

# Check if correct number of arguments are provided
if [ "$#" -ne 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign arguments to variables
file_path=$1
ip_address=$2
username=$3
ssh_key=$4

# Transfer the file using scp
scp -o StrictHostKeyChecking=no -i "$ssh_key" "$file_path" "$username@$ip_address":~/

# Check if the transfer was successful
if [ $? -eq 0 ]; then
    echo "File transfer completed successfully."
else
    echo "Error: File transfer failed."
fi
