#!/usr/bin/env bash
# This script is displaying "Best School" 10 times using while loop and display Best School the Hi on the 9th iteration

i=0

while ((i < 10)); do
	echo "Best School"
	((i++))
	if ((i == 9)); then
		echo "Hi"
	fi
done
