#!/usr/bin/env bash
# Script that accepts one argument and run the whoami command under the user passed as an argument

if [ "$#" -ne 1 ]; then
	echo "Usage: $0 <username>"
	exit 1
fi

su -c "whoami" $1
